import type { ThemeBlocks } from "@wechat-flow/contracts";

export const headingBlocks: ThemeBlocks = {
  h1: {
    "font-family": "'SF Pro Display', 'Inter', 'Helvetica Neue', Arial, sans-serif",
    "font-size": "24px",
    "font-weight": "600",
    color: "#E6EDF3",
    "line-height": "1.3",
    margin: "0 0 16px",
    "text-align": "left",
  },
  h2: {
    "font-family": "'SF Pro Display', 'Inter', 'Helvetica Neue', Arial, sans-serif",
    "font-size": "20px",
    "font-weight": "600",
    color: "#E6EDF3",
    "line-height": "1.35",
    margin: "0 0 14px",
    "text-align": "left",
  },
  h3: {
    "font-family": "'SF Pro Display', 'Inter', 'Helvetica Neue', Arial, sans-serif",
    "font-size": "18px",
    "font-weight": "600",
    color: "#E6EDF3",
    "line-height": "1.4",
    margin: "0 0 12px",
    "text-align": "left",
  },
  h4: {
    "font-family": "'SF Pro Display', 'Inter', 'Helvetica Neue', Arial, sans-serif",
    "font-size": "16px",
    "font-weight": "500",
    color: "#E6EDF3",
    "line-height": "1.4",
    margin: "0 0 10px",
    "text-align": "left",
  },
  h5: {
    "font-family": "'SF Pro Display', 'Inter', 'Helvetica Neue', Arial, sans-serif",
    "font-size": "15px",
    "font-weight": "500",
    color: "#E6EDF3",
    "line-height": "1.4",
    margin: "0 0 8px",
    "text-align": "left",
  },
  h6: {
    "font-family": "'SF Pro Display', 'Inter', 'Helvetica Neue', Arial, sans-serif",
    "font-size": "14px",
    "font-weight": "500",
    color: "#8B949E",
    "line-height": "1.4",
    margin: "0 0 8px",
    "text-align": "left",
  },
};
