#!/usr/bin/env python3
"""
Generate the directory scaffold for a workflow framework.

Usage:
    python scaffold.py <output_dir> --manifest <manifest.yaml>

The manifest describes the agents, skills, and workflows to scaffold.
This script creates the directory structure with placeholder-free skeleton files
that are ready for the LLM to fill with content.

Exit codes:
    0 = scaffold created successfully
    1 = error
    2 = invalid arguments
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path


def create_directory_structure(output_dir: Path, manifest: dict) -> list[str]:
    """Create the full directory tree. Returns list of created paths."""
    created: list[str] = []
    cataforge = output_dir / ".cataforge"

    # Core directories
    dirs = [
        cataforge,
        cataforge / "agents",
        cataforge / "skills",
        cataforge / "workflows",
        cataforge / "hooks",
        cataforge / "rules",
        cataforge / "schemas",
        output_dir / "docs",
    ]

    # Agent directories
    for agent in manifest.get("agents", []):
        agent_id = agent.get("id", agent.get("agent_id", ""))
        if agent_id:
            dirs.append(cataforge / "agents" / agent_id)

    # Skill directories
    for skill in manifest.get("skills", []):
        skill_id = skill.get("id", skill.get("skill_id", ""))
        if skill_id:
            dirs.append(cataforge / "skills" / skill_id)

    # Platform directory
    platform_id = manifest.get("platform_id", "claude-code")
    dirs.append(cataforge / "platforms" / platform_id)

    # Doc output directories
    for phase in manifest.get("workflow", {}).get("phases", []):
        phase_id = phase.get("id", "")
        if phase_id:
            dirs.append(output_dir / "docs" / phase_id)

    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
        created.append(str(d.relative_to(output_dir)))

    return created


def create_framework_json(output_dir: Path, manifest: dict):
    """Create framework.json from manifest."""
    platform_id = manifest.get("platform_id", "claude-code")
    workflow_name = manifest.get("workflow_name", "Generated Workflow")

    data = {
        "version": "1.0.0",
        "runtime_api_version": "1.0",
        "runtime": {
            "platform": platform_id,
        },
        "description": f"{workflow_name} - Generated by workflow-framework-generator.",
        "upgrade": {
            "source": {
                "type": "local",
                "note": "Generated framework - configure remote source if needed",
            },
            "state": {
                "last_commit": "",
                "last_version": "",
                "last_upgrade_date": "",
            },
        },
        "constants": manifest.get("constants", {
            "MAX_QUESTIONS_PER_BATCH": 3,
            "MAX_REVISION_CYCLES": 3,
        }),
        "features": manifest.get("features", {}),
    }

    framework_json = output_dir / ".cataforge" / "framework.json"
    framework_json.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


# NAV-INDEX.md generation removed — the chapter index is now machine-only at
# docs/.doc-index.json, produced by `cataforge docs index` once the first
# document lands. Scaffolding an empty markdown file confused agents into
# treating it as the source of truth.


def scaffold(output_dir: str, manifest: dict) -> int:
    """Create the full scaffold. Returns 0 on success."""
    root = Path(output_dir)

    if root.exists() and any(root.iterdir()):
        # Check if .cataforge already exists
        if (root / ".cataforge").exists():
            print(f"Warning: .cataforge/ already exists in {output_dir}, skipping scaffold")
            return 0

    print(f"Creating scaffold in: {root}")

    # 1. Create directories
    created = create_directory_structure(root, manifest)
    print(f"  Created {len(created)} directories")

    # 2. Create framework.json
    create_framework_json(root, manifest)
    print("  Created framework.json")

    # 3. (NAV-INDEX.md no longer generated — `cataforge docs index` now owns
    #    the chapter index at docs/.doc-index.json once docs land.)

    # 4. Create empty hooks.yaml
    hooks_file = root / ".cataforge" / "hooks" / "hooks.yaml"
    hooks_content = (
        "# Hook Specification\n"
        "# Platform-agnostic hook definitions.\n\n"
        "hooks:\n"
        "  PreToolUse: []\n"
        "  PostToolUse: []\n"
        "  Stop: []\n"
        "  SessionStart: []\n"
    )
    hooks_file.write_text(hooks_content, encoding="utf-8")
    print("  Created hooks/hooks.yaml")

    print(f"\nScaffold complete. {len(created)} directories created.")
    print("Next: generate AGENT.md, SKILL.md, and workflow YAML files.")
    return 0


def main():
    if len(sys.argv) < 4 or "--manifest" not in sys.argv:
        print(f"Usage: {sys.argv[0]} <output_dir> --manifest <manifest.yaml>")
        sys.exit(2)

    output_dir = sys.argv[1]
    manifest_idx = sys.argv.index("--manifest")
    if manifest_idx + 1 >= len(sys.argv):
        print("Error: --manifest requires a file path argument")
        sys.exit(2)

    manifest_path = sys.argv[manifest_idx + 1]

    if not os.path.isfile(manifest_path):
        print(f"Error: manifest file not found: {manifest_path}")
        sys.exit(2)

    import yaml
    with open(manifest_path, encoding="utf-8") as f:
        manifest = yaml.safe_load(f)

    if not isinstance(manifest, dict):
        print("Error: manifest must be a YAML mapping")
        sys.exit(2)

    sys.exit(scaffold(output_dir, manifest))


if __name__ == "__main__":
    main()
