export const CSS_SAFE_PROPERTIES: ReadonlySet<string> = new Set([
  // Font
  "font-family",
  "font-size",
  "font-weight",
  "font-style",
  "font-variant",
  "font",
  "line-height",
  "letter-spacing",
  "word-spacing",
  // Color & background
  "color",
  "background",
  "background-color",
  "background-image",
  "background-position",
  "background-size",
  "background-repeat",
  "background-attachment",
  "background-clip",
  "opacity",
  // Box model
  "margin",
  "margin-top",
  "margin-right",
  "margin-bottom",
  "margin-left",
  "padding",
  "padding-top",
  "padding-right",
  "padding-bottom",
  "padding-left",
  "border",
  "border-top",
  "border-right",
  "border-bottom",
  "border-left",
  "border-width",
  "border-top-width",
  "border-right-width",
  "border-bottom-width",
  "border-left-width",
  "border-style",
  "border-top-style",
  "border-right-style",
  "border-bottom-style",
  "border-left-style",
  "border-color",
  "border-top-color",
  "border-right-color",
  "border-bottom-color",
  "border-left-color",
  "border-radius",
  "border-top-left-radius",
  "border-top-right-radius",
  "border-bottom-left-radius",
  "border-bottom-right-radius",
  "width",
  "max-width",
  "min-width",
  "height",
  "max-height",
  "min-height",
  "box-sizing",
  "box-shadow",
  // Text
  "text-align",
  "text-decoration",
  "text-decoration-color",
  "text-decoration-line",
  "text-decoration-style",
  "text-indent",
  "text-shadow",
  "text-transform",
  "white-space",
  "word-break",
  "word-wrap",
  "overflow-wrap",
  "vertical-align",
  "direction",
  // Display / layout (safe subset)
  "display",
  "overflow",
  "overflow-x",
  "overflow-y",
  // List
  "list-style",
  "list-style-type",
  "list-style-position",
  "list-style-image",
  // Table
  "border-collapse",
  "border-spacing",
  "caption-side",
  "empty-cells",
  "table-layout",
  // Cursor
  "cursor",
  // Outline (safe for accessibility)
  "outline",
  "outline-color",
  "outline-style",
  "outline-width",
]);

export function isWhitelistedProperty(prop: string): boolean {
  return CSS_SAFE_PROPERTIES.has(prop.toLowerCase().trim());
}
