import type { TokenDefinition } from "./token-types.ts";

export const DESIGN_TOKENS: TokenDefinition[] = [
  // color (ui-spec §1.1)
  { id: "color.surface", category: "color", value: "#FAF8F5" },
  { id: "color.surface-elevated", category: "color", value: "#FFFFFF" },
  { id: "color.surface-sunken", category: "color", value: "#F2EFE9" },
  { id: "color.border", category: "color", value: "#D9D4CB" },
  { id: "color.border-strong", category: "color", value: "#BDB8B0" },
  { id: "color.text-primary", category: "color", value: "#1C1917" },
  { id: "color.text-secondary", category: "color", value: "#78716C" },
  { id: "color.text-tertiary", category: "color", value: "#A8A29E" },
  { id: "color.text-disabled", category: "color", value: "#C7C2BB" },
  { id: "color.brand", category: "color", value: "#2D5A4E" },
  { id: "color.brand-hover", category: "color", value: "#245148" },
  { id: "color.brand-subtle", category: "color", value: "#E8F0EE" },
  { id: "color.accent", category: "color", value: "#B94A3E" },
  { id: "color.accent-hover", category: "color", value: "#A5423A" },
  { id: "color.accent-subtle", category: "color", value: "#FAECEA" },
  { id: "color.success", category: "color", value: "#3A6B49" },
  { id: "color.success-subtle", category: "color", value: "#E6F0E9" },
  { id: "color.error", category: "color", value: "#B94A3E" },
  { id: "color.error-subtle", category: "color", value: "#FAECEA" },
  { id: "color.warning", category: "color", value: "#A16207" },
  { id: "color.warning-subtle", category: "color", value: "#FEF9EE" },
  { id: "color.overlay", category: "color", value: "rgba(28,25,23,0.5)" },

  // font (ui-spec §1.2)
  {
    id: "font.family-sans",
    category: "font",
    value: "-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif",
  },
  { id: "font.family-serif", category: "font", value: "Georgia,'Times New Roman',serif" },
  {
    id: "font.family-mono",
    category: "font",
    value: "'SFMono-Regular',Consolas,'Liberation Mono',monospace",
  },
  { id: "font.size-xs", category: "font", value: "12px" },
  { id: "font.size-sm", category: "font", value: "13px" },
  { id: "font.size-base", category: "font", value: "15px" },
  { id: "font.size-md", category: "font", value: "16px" },
  { id: "font.size-lg", category: "font", value: "18px" },
  { id: "font.size-xl", category: "font", value: "20px" },
  { id: "font.size-2xl", category: "font", value: "24px" },
  { id: "font.line-height-tight", category: "font", value: "1.3" },
  { id: "font.line-height-base", category: "font", value: "1.6" },
  { id: "font.line-height-relaxed", category: "font", value: "1.8" },
  { id: "font.weight-normal", category: "font", value: "400" },
  { id: "font.weight-medium", category: "font", value: "500" },
  { id: "font.weight-bold", category: "font", value: "700" },

  // spacing (ui-spec §1.3)
  { id: "spacing.space-1", category: "spacing", value: "4px" },
  { id: "spacing.space-2", category: "spacing", value: "8px" },
  { id: "spacing.space-3", category: "spacing", value: "12px" },
  { id: "spacing.space-4", category: "spacing", value: "16px" },
  { id: "spacing.space-6", category: "spacing", value: "24px" },
  { id: "spacing.space-8", category: "spacing", value: "32px" },
  { id: "spacing.radius-base", category: "spacing", value: "4px" },
  { id: "spacing.radius-md", category: "spacing", value: "6px" },
  { id: "spacing.radius-lg", category: "spacing", value: "8px" },
  { id: "spacing.radius-xl", category: "spacing", value: "12px" },

  // decoration (ui-spec §1.4)
  { id: "decoration.shadow-sm", category: "decoration", value: "0 1px 3px rgba(28,25,23,0.08)" },
  { id: "decoration.shadow-base", category: "decoration", value: "0 2px 8px rgba(28,25,23,0.12)" },
  { id: "decoration.shadow-md", category: "decoration", value: "0 4px 16px rgba(28,25,23,0.16)" },
  { id: "decoration.shadow-lg", category: "decoration", value: "0 8px 32px rgba(28,25,23,0.20)" },
  { id: "decoration.z-base", category: "decoration", value: "1" },
  { id: "decoration.z-dropdown", category: "decoration", value: "100" },
  { id: "decoration.z-toolbar", category: "decoration", value: "200" },
  { id: "decoration.z-modal", category: "decoration", value: "300" },
  { id: "decoration.z-toast", category: "decoration", value: "400" },
  { id: "decoration.z-tooltip", category: "decoration", value: "500" },
  { id: "decoration.transition-fast", category: "decoration", value: "120ms ease" },
  { id: "decoration.transition-base", category: "decoration", value: "200ms ease" },
  { id: "decoration.transition-slow", category: "decoration", value: "300ms ease" },

  // alignment (ui-spec §1.6)
  { id: "alignment.bp-tablet", category: "alignment", value: "768px" },
  { id: "alignment.bp-desktop", category: "alignment", value: "1280px" },
];
