import type { ThemeBlocks } from "@wechat-flow/contracts";

export const headingBlocks: ThemeBlocks = {
  h1: {
    "font-family": "'PingFang SC', 'Helvetica Neue', Arial, 'Microsoft YaHei', sans-serif",
    "font-size": "26px",
    "font-weight": "700",
    color: "#1A1208",
    "line-height": "1.3",
    margin: "0 0 20px",
    "text-align": "left",
  },
  h2: {
    "font-family": "'PingFang SC', 'Helvetica Neue', Arial, 'Microsoft YaHei', sans-serif",
    "font-size": "22px",
    "font-weight": "700",
    color: "#1A1208",
    "line-height": "1.35",
    margin: "0 0 16px",
    "text-align": "left",
  },
  h3: {
    "font-family": "'PingFang SC', 'Helvetica Neue', Arial, 'Microsoft YaHei', sans-serif",
    "font-size": "19px",
    "font-weight": "600",
    color: "#1A1208",
    "line-height": "1.4",
    margin: "0 0 14px",
    "text-align": "left",
  },
  h4: {
    "font-family": "'PingFang SC', 'Helvetica Neue', Arial, 'Microsoft YaHei', sans-serif",
    "font-size": "17px",
    "font-weight": "600",
    color: "#1A1208",
    "line-height": "1.4",
    margin: "0 0 12px",
    "text-align": "left",
  },
  h5: {
    "font-family": "'PingFang SC', 'Helvetica Neue', Arial, 'Microsoft YaHei', sans-serif",
    "font-size": "16px",
    "font-weight": "500",
    color: "#1A1208",
    "line-height": "1.4",
    margin: "0 0 10px",
    "text-align": "left",
  },
  h6: {
    "font-family": "'PingFang SC', 'Helvetica Neue', Arial, 'Microsoft YaHei', sans-serif",
    "font-size": "15px",
    "font-weight": "500",
    color: "#4A3728",
    "line-height": "1.4",
    margin: "0 0 8px",
    "text-align": "left",
  },
};
