import type { ThemeTokens } from "@wechat-flow/contracts";

export const tokens: ThemeTokens = {
  // color — 21 tokens
  "--color-background": "#faf8f5",
  "--color-surface": "#faf8f5",
  "--color-surface-alt": "#f3f0eb",
  "--color-text-primary": "#1c1917",
  "--color-text-secondary": "#44403c",
  "--color-text-muted": "#78716c",
  "--color-text-inverse": "#fafaf9",
  "--color-brand": "#2d5a4e",
  "--color-brand-light": "#3d7a68",
  "--color-brand-dark": "#1e3d35",
  "--color-accent": "#b94a3e",
  "--color-accent-light": "#d45e51",
  "--color-accent-dark": "#8f3830",
  "--color-border": "#d6d3ce",
  "--color-border-strong": "#a8a29e",
  "--color-code-bg": "#f0ede8",
  "--color-code-block-bg": "#f0ede8",
  "--color-code-text": "#292524",
  "--color-quote-border": "#2d5a4e",
  "--color-quote-bg": "#f3f0eb",
  "--color-link": "#2d5a4e",

  // spacing — 14 tokens
  "--spacing-xs": "4px",
  "--spacing-sm": "8px",
  "--spacing-md": "12px",
  "--spacing-lg": "16px",
  "--spacing-xl": "24px",
  "--spacing-2xl": "32px",
  "--spacing-3xl": "48px",
  "--spacing-paragraph-bottom": "12px",
  "--spacing-heading-bottom": "16px",
  "--spacing-list-item": "6px",
  "--spacing-code-inline-h": "4px",
  "--spacing-code-inline-v": "2px",
  "--spacing-blockquote-h": "16px",
  "--spacing-blockquote-v": "10px",

  // font — 16 tokens
  "--font-family-body": "'LXGW WenKai', 'Source Han Serif CN', 'Noto Serif CJK SC', Georgia, serif",
  "--font-family-heading":
    "'LXGW WenKai', 'Source Han Serif CN', 'Noto Serif CJK SC', Georgia, serif",
  "--font-family-mono": "'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace",
  "--font-size-base": "15px",
  "--font-size-sm": "13px",
  "--font-size-lg": "17px",
  "--font-size-h1": "22px",
  "--font-size-h2": "19px",
  "--font-size-h3": "17px",
  "--font-size-h4": "16px",
  "--font-size-h5": "15px",
  "--font-size-h6": "14px",
  "--font-weight-normal": "400",
  "--font-weight-medium": "500",
  "--font-weight-bold": "700",
  "--font-line-height-body": "1.85",

  // decoration — 6 tokens
  "--decoration-hr-color": "#d6d3ce",
  "--decoration-hr-style": "solid",
  "--decoration-hr-width": "1px",
  "--decoration-border-radius-sm": "3px",
  "--decoration-border-radius-md": "6px",
  "--decoration-link-underline": "underline",

  // alignment — 4 tokens
  "--align-text-body": "left",
  "--align-text-heading": "left",
  "--align-text-caption": "center",
  "--align-list-marker": "outside",
};
