import type { ThemeBlocks } from "@wechat-flow/contracts";

export const headingBlocks: ThemeBlocks = {
  h1: {
    "font-family": "'LXGW WenKai', 'Source Han Serif CN', 'Noto Serif CJK SC', Georgia, serif",
    "font-size": "22px",
    "font-weight": "700",
    color: "#1C1917",
    "line-height": "1.4",
    margin: "0 0 16px",
    "text-align": "left",
  },
  h2: {
    "font-family": "'LXGW WenKai', 'Source Han Serif CN', 'Noto Serif CJK SC', Georgia, serif",
    "font-size": "19px",
    "font-weight": "700",
    color: "#1C1917",
    "line-height": "1.4",
    margin: "0 0 14px",
    "text-align": "left",
  },
  h3: {
    "font-family": "'LXGW WenKai', 'Source Han Serif CN', 'Noto Serif CJK SC', Georgia, serif",
    "font-size": "17px",
    "font-weight": "700",
    color: "#1C1917",
    "line-height": "1.4",
    margin: "0 0 12px",
    "text-align": "left",
  },
  h4: {
    "font-family": "'LXGW WenKai', 'Source Han Serif CN', 'Noto Serif CJK SC', Georgia, serif",
    "font-size": "16px",
    "font-weight": "500",
    color: "#1C1917",
    "line-height": "1.4",
    margin: "0 0 10px",
    "text-align": "left",
  },
  h5: {
    "font-family": "'LXGW WenKai', 'Source Han Serif CN', 'Noto Serif CJK SC', Georgia, serif",
    "font-size": "15px",
    "font-weight": "500",
    color: "#1C1917",
    "line-height": "1.4",
    margin: "0 0 8px",
    "text-align": "left",
  },
  h6: {
    "font-family": "'LXGW WenKai', 'Source Han Serif CN', 'Noto Serif CJK SC', Georgia, serif",
    "font-size": "14px",
    "font-weight": "500",
    color: "#44403C",
    "line-height": "1.4",
    margin: "0 0 8px",
    "text-align": "left",
  },
};
